sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- node
script:
- npm run test-ci
- npm run build-ci
before_install:
- pip install --user codecov
after_success:
- codecov --file coverage/lcov.info --disable search
