name: CI

on: push

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     - uses: actions/setup-node@v1
       with:
        node-version: "14.x"
     - run: npm ci
     - run: npm run lint
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: "14.x"
    - run: npm ci
    - run: npm run test-ci
    - uses: codecov/codecov-action@v1
      with:
        fail_ci_if_error: true
        directory: coverage
